# -*- coding: utf-8 -*-
"""P04-19921122.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_laC6hn3Rj6b5-L7nm7KSveD1kkZ8nXS

Identitas Diri
"""

# Nama      : Salma Sari Juliani
# NIM       : 19921122
# Deskripsi : Praktikum Pengenalan Komputasi Modul 4

"""Code"""

# Import data
import pandas as pd
import matplotlib as plt
import matplotlib.pyplot as plt

# Membaca data
data_frame = pd.read_csv('data_mahasiswa.csv')

"""a. Buat pie chart banyaknya mahasiswa tiap gender."""

mycolors = ["lightskyblue", "greenyellow", "lightsalmon"]
data_frame["gender"].value_counts().plot(kind = "pie", colors=mycolors, autopct='%1.1f%%', title="Persentase Banyak Mahasiswa per Gender")
plt.show()

"""b. Informasi apa yang bisa Anda ambil berdasarkan chart sebelumnya? Tuliskan dalam komentar."""

# Berdasarkan visualisasi pie chart di atas, banyaknya selisih mahasiswa laki-laki dan perempuan cukup jauh. 
# Mahasiswa didominasi oleh laki-laki (male) dengan persentase sebanyak 81.6%, sedangkan mahasiswa perempuan (female) lebih sedikit
# dengan persentase hanya 18.4%.

"""c. Buat bar chart dengan fakultas sebagai sumbu x 
dan jumlah mahasiswa dengan tinggi di atas 160 sebagai sumbu y. 
"""

datas = data_frame.loc[(data_frame['tinggi'] > 160)]
datas.groupby("fakultas")["tinggi"].size().plot(kind='bar', color='pink', title='Jumlah Mahasiswa dengan Tinggi diatas 160 per Fakultas')
plt.show()

"""d. Buat histogram dengan tinggi sebagai sumbu x dan jumlah mahasiswa laki-laki sebagai sumbu y."""

datas1 = data_frame.loc[(data_frame['gender'] == 'M')]
datas1[["tinggi"]].plot(kind="hist", bins=[150, 155, 160, 165, 170, 175, 180,185,190], rwidth=0.8, color='lightgreen', title='Banyaknya Mahasiswa Laki-Laki Berdasarkan Tinggi Tertentu')
plt.show()

"""e. Scatter plot dengan berat badan sebagai sumbu x dan tinggi badan sebagai sumbu y"""

data_frame.plot(kind="scatter", x="berat", y="tinggi", color="violet", title="Korelasi Berat Badan dengan Tinggi Mahasiswa")
plt.show()

"""f. Buat stacked bar chart dengan fakultas sebagai sumbu x dan jumlah mahasiswa tiap gender sebagai sumbu y"""

mycolors=['pink', 'grey']
data_frame.groupby(["fakultas","gender"])["nama"].size().unstack().plot(kind="bar",stacked=True, color=mycolors, title="Jumlah Mahasiswa Berdasarkan Gender per Fakultas")
plt.show()

"""g. Informasi apa yang bisa anda ambil berdasarkan chart sebelumnya? Tulis dalam komentar."""

# Berdasarkan visualisasi di atas, terlihat bahwa dari setiap fakultas perbandingan jumlah laki-laki dan perempuannya cukup jauh

"""h. Buat line chart dengan berat badan sebagai sumbu x dan jumlah mahasiswa sebagai sumbu y"""

datas2 = data_frame.groupby("berat")["nama"].size()
datas2.plot(kind='line', color='cyan', title='Jumlah Mahasiswa Berdasarkan Berat Badan')
plt.show()

"""i. Buat line chart seperti soal sebelumnya, namun terdapat dua garis, masing-masing untuk tiap gender."""

Male = data_frame[data_frame['gender'] == 'M'].groupby('berat').size()
Female = data_frame[data_frame['gender'] == 'F'].groupby('berat').size()

plt.plot(Male, color='green')
plt.plot(Female, color='grey')
plt.legend(['Male', 'Female'])
plt.title('Jumlah Mahasiswa Berdasarkan Berat Badan per Gender')
plt.show()

"""j. Informasi apa yang bisa anda ambil dari chart sebelumnya? Tuliskan dalam komentar"""

# Mahasiswa perempuan paling banyak memiliki berat badan di kisaran 40-50, sedangkan mahasiswa laki-laki paling banyak memiliki berat badan di kisaran 60-80.