# -*- coding: utf-8 -*-
"""TP04-19921122.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MywNmRs70YInLHNTlsarzrzc_nSK21z5

Identitas Diri
"""

# Nama      : Salma Sari Juliani
# NIM       : 19921122
# Deskripsi : Tugas Pendahuluan Modul 4

"""Code

1. Baca data pada tiap sheet tersebut. Lihat bagaimana 5
entri pertama masing-masing data.
"""

# Import data.
import pandas as pd
import matplotlib as plt
import matplotlib.pyplot as plt


# Membaca data dari setiap sheet.
data_frame_1 = pd.read_excel("data pengkom.xlsx", sheet_name="Sheet1")
data_frame_2 = pd.read_excel("data pengkom.xlsx", sheet_name="Sheet2")
data_frame_3 = pd.read_excel("data pengkom.xlsx", sheet_name="Sheet3")

# Lima entri pertama pada data di sheet 1.
data_frame_1.head()

# Lima entri pertama pada data di sheet 2.
data_frame_2.head()

# Lima entri pertama pada data di sheet 3.
data_frame_3.head()

"""2. Dari data pada Sheet 1, buat horizontal bar chart tiap harga makanan.

"""

# Horizontal bar chart untuk menampilkan harga dari setiap makanan
data_frame_1.plot(kind="barh",x="nama",y="harga",title="Harga Setiap Makanan", color="turquoise")
plt.show()

"""3. Dari data pada Sheet 2, buat histogram tinggi badan dengan kelompok tinggi 100-110,
110-120, 120-130, 130-140, 140-150, 150-160.
"""

# Histogram tinggi badan berdasarkan kelompok tinggi: 100-110; 110-120; 120-130; 130-140; 140-150; 150-160. 
data_frame_2[["tinggi_anak"]].plot(kind="hist", bins=[100,110,120,130,140,150,160], rwidth=0.8, color="lightcoral", title="Frekuensi Tinggi Badan")
plt.show()

"""4. Dari data pada Sheet 1, buat pie chart komposisi banyaknya makanan pada tiap jenis."""

# Komposisi banyaknya makanan pada tiap jenis
mycolors = ["lightskyblue", "greenyellow", "lightsalmon"]
data_frame_1["jenis"].value_counts().plot(kind = "pie", colors=mycolors, autopct='%1.1f%%', title="Persentase Jenis Makanan")
plt.show()

"""5. Dari data pada Sheet 3, buat line chart pertumbuhan harga.

"""

# Pertumbuhan harga emas dari tahun ke tahun dalam line chart
data_frame_3.plot(kind="line",x="date",y="gold_price", color="lightgreen", title="Pertumbuhan Harga Emas")
plt.show()

"""6. Dari data pada Sheet 2, buat scatter plot dengan absis berupa tinggi anak dan ordinat
berupa berat anak.
 Apa yang dapat Anda simpulkan?
"""

# Korelasi antara variable tinggi anak dan berat anak dalam grafik scatter plot 
data_frame_2.plot(kind="scatter", x="tinggi_anak", y="berat_anak", color="violet", title="Korelasi Tinggi Anak dan Berat Anak")
plt.show()
print("")
print("Dari visualisasi di atas, grafik scatter plot menunjukkan adanya korelasi positif.") 
print("Semakin tinggi seorang anak maka berat badannya pun semakin besar.")